setting landing-page/login view and starting dashboard homepage view
newPangea/mono-repo pull request #5
Opened 2021-02-08 19:41 UTC by lcaloguerea

[[NP-3](https://pappcorn.atlassian.net/secure/RapidBoard.jspa?rapidView=112&projectKey=NP&modal=detail&selectedIssue=NP-3)]

# Change description
- Created pages structure
- Created pages/login module
- Added UI elements and set routing to dashboard
- Created Dashboard module
- Added sidebar menu (In progress)

# Evidence
Landing Page / Login using minimum resolution established by design
![imagen](https://user-images.githubusercontent.com/7730194/107272138-05012b00-6a2c-11eb-9b59-cf7108dc3898.png)

Dashboard after login in progress
![imagen](https://user-images.githubusercontent.com/7730194/107272509-8ce73500-6a2c-11eb-9a02-4de9366b914c.png)

2021-02-08 21:04 UTC, ruedagato requested changes

2021-02-08 21:04 UTC, ruedagato commented on apps/dashboard/src/styles.scss
> +  font-family: Roboto, 'Helvetica Neue', sans-serif;
this style is incorrect, the real font was already imported

2021-02-08 21:04 UTC, ruedagato commented on libs/styles/global.scss
> +.mat-form-field-appearance-fill .mat-form-field-flex {
move this to a _material.scss file and import on this

2021-02-09 02:10 UTC, lcaloguerea commented on apps/dashboard/src/app/app.component.html
> +<!-- <h1 class="text">Text primary 4</h1>
Done

2021-02-09 02:10 UTC, lcaloguerea commented on apps/dashboard/src/app/common-components/sidebar-menu/sidebar-menu.component.ts
> +/* eslint-disable @typescript-eslint/no-empty-function */
Rule has been activated

2021-02-09 02:11 UTC, lcaloguerea commented on apps/dashboard/src/app/common-components/sidebar-menu/sidebar-menu.component.ts
> +export class SidebarMenuComponent implements OnInit {
Move and build new folder structure 

- shared-components
       - components
             - sidebar-menu

2021-02-09 02:12 UTC, lcaloguerea commented on apps/dashboard/src/app/pages/login/login.component.scss
> +        font-size: 14px;
Added mixin structure

2021-02-09 02:13 UTC, lcaloguerea commented on apps/dashboard/src/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
Both fonts removed

2021-02-09 02:14 UTC, lcaloguerea commented on libs/styles/global.scss
> +.mat-form-field-appearance-fill .mat-form-field-flex {
Moved

2021-02-09 03:40 UTC, ruedagato requested changes

2021-02-09 03:40 UTC, ruedagato commented on apps/dashboard/src/app/pages/login/login.component.html
> +              <button
use pangButton like this example https://github.com/newPangea/mono-repo/blob/dev/libs/ui/src/lib/components/button/button.component.stories.ts#L8

2021-02-09 19:49 UTC, merged